### ISSUE TITLE
fix rprof legend

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#44]
if you plot only one variable, you don't need a legend

**Comment by amorison** [comment]
In the current state, you do, because the `shortname` contains less information than the `description` field in the `RPROF` and `TIME` dictionaries.

I guess if there is only one variable we could put the `description` instead of the `shortname` on the axis.

**Comment by mulvrova** [comment]
this issue does not concern ax labels. this issue concerns a legend. there should not be a legend in case you plot a single variable

**Comment by amorison** [comment]
I understand that, but what I say is that we can't just switch it off as is or we will lose information.

For example if you plot `Tmax`, the current state of things is that you will have "Temperature" on the axis and "Max temperature " on the legend instead of "Max temperature" on the axis and no legend.

**Comment by mulvrova** [comment]
i c. then i agree, we could put the `description` instead of the `shortname` on the axis

**Comment by amorison** [comment]
Fix by aea540416ce28198d2c4fca1a67b3ad6e54d7664
