### ISSUE TITLE
add zoom option for field plots  

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#45]
this is useful especially for spherical annulus models

**Comment by amorison** [comment]
How should that behave?

Looking at your implementation in the plates module, I can see you're making a zoom on some phi-position. What should be the general behavior of the option? Zooming on a specified (horizontal, vertical) position with some zoom factor?

That requires three inputs (we could have smart defaults so that it would work even when specifying only one), but it avoids the need to code "magical" values such as the ladd, radd, dadd and uadd in the current implementation the plates module.

**Comment by mulvrova** [comment]
yes, the general behaviour should be zooming around a specific place (possibly in 3D) given by the user + having a zoom factor is a good solution. 

smart defaults are definitely a good choice. we might e.g. suppose that the zoom is at surface.

one must also keep in mind to handle different geometries.

**Comment by amorison** [comment]
Closing since this is superseded by the proposition #48
