### ISSUE TITLE
stagpy in scripts - how to get stagpy processed data ? 

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#60]
how to allow users to get stagyy data in python scripts such as time averaged profiles

some questions related:

- how should we return data when a collection of plots is asked for (e.g. many variables over several timesteps)?
- what interface should be proposed for the user to be able to ask for the data themselves or the plot objects (matplotlib axes) ?

**Comment by amorison** [comment]
There is now an API for both StagPy-computed data that still missed an API.

- Time series average and rms (to study e.g. statistical steady states) through the `time_series.compstat` function (commit a61ebf5c92a4f60d1b966dd11b6a7d1840c511f3).
- Time-averaged radial profile through the `_StepsView.rprofs_averaged` property (commit de115984186af49e41c431beccf7567ecc7bbf85), e.g. `sdat.snaps[-5:].rprofs_averaged['Tmean']` is the temperature profile averaged over the last 5 snapshots. Note that shortcomings that were already present in plots obtained with the `+average` switch are still present: geometry and time steps are considered constant when computing the average profile. These need to be addressed, particularly the constant `dt` assumption.

I close this issue now since the other secondary points concern the access to plot objects which is still very limited across StagPy anyway. Work on that might happen later is there is demand for it.
